apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "^56.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      adminUser: admin
      adminPassword: admin
      service:
        type: ClusterIP
      grafana.ini:
        server:
          domain: homelab.nobeledgar3.cloud
          root_url: https://homelab.nobeledgar3.cloud/grafana
          serve_from_sub_path: true
        users:
          viewers_can_edit: false
        auth.anonymous:
          enabled: false
    prometheus:
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        routePrefix: /prometheus
        externalUrl: https://homelab.nobeledgar3.cloud/prometheus